<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Litesh" failures="1" tests="2" name="Test" time="0.04" errors="0" timestamp="2024-12-10T12:40:23 IST">
  <testcase classname="listners.example.TestngListernsEx" name="test1" time="0.007"/>
  <testcase classname="listners.example.TestngListernsEx" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at listners.example.TestngListernsEx.test2(TestngListernsEx.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
